```{r}
#| label: basetabfunc
#| cache: true
#| cache.comments: false

basetabfunc_inner <- function(x, data, stratavar, catdig, contdig, overall) {
  tmp <- data %>%
    filter(!is.na(!!sym(x)) & !is.na(!!sym(stratavar)))

  pmis <- data %>%
    filter(!is.na(!!sym(stratavar))) %>%
    mutate(mis = factor(if_else(is.na(!!sym(x)), 1, 0), levels = 0:1)) %>%
    count(mis, .drop = F) %>%
    mutate(pmis = fn(n / sum(n) * 100, catdig)) %>%
    filter(mis == "1") %>%
    pull(pmis)

  cl <- class(data %>% pull(!!sym(x)))
  if (cl %in% c("character", "factor")) {
    out <- tmp %>%
      group_by(!!sym(stratavar), .drop = F) %>%
      count(!!sym(x), .drop = F) %>%
      mutate(
        out = paste0(n, " (", fn(n / sum(n) * 100, catdig), ")"),
        out = case_when(
          sum(n) == 0 ~ "-",
          n < 10 ~ "<10",
          TRUE ~ out
        ),
        level = !!sym(x)
      ) %>%
      ungroup() %>%
      select(!!sym(stratavar), out, level) %>%
      pivot_wider(names_from = !!sym(stratavar), values_from = out)

    # p-value
    check <- tmp %>%
      count(!!sym(stratavar), !is.na(!!sym(x)))
    if (nrow(check) >= 2) {
      p <- fn(chisq.test(tmp %>% pull(!!sym(stratavar)), tmp %>% pull(!!sym(x)))$p.value, p = T, dig = 3)
    } else {
      p <- "-"
    }

    if (overall) {
      outall <- data %>%
        filter(!is.na(!!sym(x))) %>%
        count(!!sym(x), .drop = F) %>%
        mutate(
          Overall = paste0(n, " (", fn(n / sum(n) * 100, catdig), ")"),
          Overall = case_when(
            sum(n) == 0 ~ "-",
            n < 10 ~ "<10",
            TRUE ~ Overall
          ),
          level = !!sym(x)
        ) %>%
        select(level, Overall)

      out <- full_join(outall, out, by = "level")
    }

    # if levels No, Yes only present Yes
    levs <- out %>% pull(level)
    nlevs <- length(levs)
    if (nlevs == 2 & all(levs %in% c("No", "Yes"))) {
      out <- out %>%
        filter(level == "Yes") %>%
        mutate(
          var = x,
          p = p,
          pmis = pmis,
          level = NA
        )
    } else {
      out <- out %>%
        mutate(
          var = NA,
          p = NA,
          pmis = NA
        )
      out <- out %>% add_row(
        var = x,
        p = p,
        pmis = pmis,
        .before = 1
      )
    }
  } else if (cl %in% c("numeric", "integer")) {
    if (length(contdig) > 1) {
      if (any(contdig$vars %in% x)) {
        contdig <- contdig %>%
          filter(vars == x) %>%
          pull(contdig)
      } else {
        contdig <- 0
      }
    }
    out <- tmp %>%
      group_by(!!sym(stratavar), .drop = F) %>%
      reframe(
        med = quantile(!!sym(x), na.rm = T, probs = c(0.5)),
        q1 = quantile(!!sym(x), na.rm = T, probs = c(0.25)),
        q3 = quantile(!!sym(x), na.rm = T, probs = c(0.75)),
        mean = mean(!!sym(x), na.rm = T),
        sd = sd(!!sym(x), na.rm = T),
        min = min(!!sym(x), na.rm = T),
        max = max(!!sym(x), na.rm = T),
        n = n()
      ) %>%
      mutate(
        out = paste0(
          fn(med, contdig), " [", fn(min, contdig), ", ", fn(q1, contdig), ", ",
          fn(q3, contdig), ", ", fn(max, contdig), "], ", fn(mean, contdig), " (", fn(sd, contdig), ")"
        ),
        out = case_when(
          n == 0 ~ "-",
          n < 10 ~ "<10",
          TRUE ~ out
        )
      ) %>%
      ungroup() %>%
      select(!!sym(stratavar), out) %>%
      pivot_wider(names_from = !!sym(stratavar), values_from = out)

    # p-value
    check <- tmp %>%
      count(!!sym(stratavar), !is.na(!!sym(x)))
    if (nrow(check) >= 2) {
      p <- fn(kruskal.test(formula(paste0(x, " ~ ", stratavar)), data = tmp)$p.value, p = T, dig = 3)
    } else {
      p <- "-"
    }

    if (overall) {
      outall <- data %>%
        filter(!is.na(!!sym(x))) %>%
        summarise(
          med = quantile(!!sym(x), na.rm = T, probs = c(0.5)),
          q1 = quantile(!!sym(x), na.rm = T, probs = c(0.25)),
          q3 = quantile(!!sym(x), na.rm = T, probs = c(0.75)),
          mean = mean(!!sym(x), na.rm = T),
          sd = sd(!!sym(x), na.rm = T),
          min = min(!!sym(x), na.rm = T),
          max = max(!!sym(x), na.rm = T),
          n = n()
        ) %>%
        mutate(
          Overall = paste0(
            fn(med, contdig), " [", fn(min, contdig), ", ", fn(q1, contdig), ", ",
            fn(q3, contdig), ", ", fn(max, contdig), "], ", fn(mean, contdig), " (", fn(sd, contdig), ")"
          ),
          Overall = case_when(
            n == 0 ~ "-",
            n < 10 ~ "<10",
            TRUE ~ Overall
          )
        ) %>%
        select(Overall)

      out <- bind_cols(outall, out)
    }

    out <- out %>%
      mutate(
        var = x,
        p = p,
        pmis = pmis
      )
  } else {
    stop("Unknown class in baseline table")
  }
}

contdig <- tibble(vars = c("shf_potassium"), contdig = 1)
catdig <- 0

basetabfunc <- function(data, novars = NULL, stratavar, overall = F, tabheader, fs = 6, cs = "4cm") {
  tab <- data %>%
    count(!!sym(stratavar), .drop = F) %>%
    mutate(n = paste0(n, " (", fn(n / sum(n) * 100, catdig), ")")) %>%
    pivot_wider(names_from = !!sym(stratavar), values_from = n) %>%
    mutate(
      var = "N (%)",
      level = NA,
      p = NA,
      pmis = NA
    ) %>%
    select(var, level, pmis, levels(data %>% pull(!!sym(stratavar))), p)

  if (overall) {
    taboverall <- data %>%
      count() %>%
      mutate(
        n = paste0(n)
      )

    tab <- tab %>%
      add_column(
        Overall = taboverall %>% pull(n),
        .before = 4
      )
  }

  tabvarstmp <- setdiff(tabvars, novars)
  tabtmp <- sapply(tabvarstmp,
    FUN = basetabfunc_inner, data = data,
    stratavar = stratavar, catdig = catdig, contdig = contdig, overall = overall
  )

  tabtmp <- bind_rows(tabtmp)
  tab <- bind_rows(tab, tabtmp)

  tab <- tab %>%
    mutate(
      # if recoding or categorizing will still get org label
      var_tmp = str_replace_all(var, "(_cat2|_cat)", ""),
      # if shf/sos combination  will still get org label
      var_tmp = str_replace_all(var_tmp, "shf_sos_com_", "sos_com_")
    )

  tab <- left_join(tab,
    metavars %>%
      select(variable, label, unit),
    by = c("var_tmp" = "variable")
  ) %>%
    mutate(
      Variable = coalesce(label, var_tmp),
      Variable = if_else(!is.na(unit),
        paste0(Variable, " (", unit, ")"),
        Variable
      ),
      Variable = if_else(!is.na(level) & !is.na(Variable),
        paste0(Variable, " ", level),
        coalesce(Variable, paste0("  ", level))
      ),
      # small fixes
      Variable = str_replace_all(Variable, fixed("Disposable income (100 SEK)"), "Income"),
      pmis = if_else(var_tmp == "sos_hospward_3mo", "0", pmis)
    )

  # footnotes
  tab <- tab %>%
    mutate(
      footnote1 = if_else(!is.na(var) & var %in% modvars, footnote_marker_alphabet(1, format = "latex"), "")
    ) %>%
    unite(footnote, starts_with("footnote"), sep = "")

  if (overall) {
    cn <- c("Variable", "Missing (%)", "Overall", levels(data %>% pull(!!sym(stratavar))), "p-value")
  } else {
    cn <- c("Variable", "Missing (%)", levels(data %>% pull(!!sym(stratavar))), "p-value")
  }

  footnotetext <- c(
    "Included in multiple imputation and regression models."
  )

  # excel
  tab_xls <- tab %>%
    mutate(
      Variable = paste0(Variable, footnote),
      Variable = str_remove_all(Variable, "textsuperscript|\\}|\\{"),
      Variable = str_replace_all(Variable, "\\\\", " ")
    ) %>%
    select(Variable, pmis:p) %>%
    add_row(Variable = "") %>%
    add_row(Variable = paste0("a ", footnotetext[1]))

  make_one_xlsxsheet(tab_xls, colnames = cn)

  # footnotes
  tab <- tab %>%
    mutate(
      # so no probs
      Variable = sanitize_text(Variable),
      Variable = paste0(Variable, footnote),
      Variable = str_replace_all(Variable, fixed("²"), "\\textsuperscript{2}"),
      Variable = str_replace_all(Variable, fixed("$>$="), "$\\geq$"),
      Variable = str_replace_all(Variable, fixed("$<$="), "$\\leq$")
    ) %>%
    select(Variable, pmis:p)

  indent_rows <- tab %>%
    mutate(
      indent_rows = str_detect(Variable, "  "),
      rows = row_number()
    ) %>%
    filter(indent_rows) %>%
    pull(rows)

  cn <- sanitize_text(cn)

  ce <- if_else(overall, 3, 2)
  nl <- nlevels(data %>% pull(!!sym(stratavar)))

  if (overall) {
    colspec <- c(1, 3:(3 + nl))
  } else {
    colspec <- c(1, 3:(2 + nl))
  }

  header <- c(ce, nl, 1)
  names(header) <- c(" ", tabheader, " ")

  default_kable(tab,
    font_size = fs,
    longtable = TRUE,
    escape = FALSE,
    col.names = cn
  ) %>%
    add_indent(indent_rows) %>%
    add_header_above(header = header) %>%
    footnote(
      footnote_order = c("general", "symbol", "alphabet"),
      general_title = "",
      general = c(
        "Categorical variables are presented with n (%) and tested with chi-square test and continuous variables with median [minimum, q1, q3, maximum], mean (standard deviation) and tested with Kruskal-Wallis test."
      ),
      alphabet = footnotetext,
      threeparttable = T
    ) %>%
    column_spec(colspec, width = cs) %>%
    row_spec(1, hline_after = T)
}
```

```{r}
#| label: tbl-base
#| cache: true
#| cache.comments: false
#| dependson: basetabfunc
#| tbl-cap: "Baseline characteristics by previous HFH within 3 months"
#| tbl-pos: "H"

basetabfunc(data = rsdata, stratavar = "sos_prevhfh3mo", novars = c("sos_prevhfh3mo"), overall = T, tabheader = "Previous HFH within 3 months")
```

```{r}
#| label: tbl-base-nogdmt
#| cache: true
#| cache.comments: false
#| dependson: basetabfunc
#| tbl-cap: "Baseline characteristics by Guideline-directed medical therapy"
#| tbl-pos: "H"

basetabfunc(
  data = rsdata, stratavar = "sos_lm_gdmt", novars = c("sos_lm_gdmt"), overall = T,
  tabheader = "Guideline-directed medical therapy", cs = "2.5cm"
)
```
