
```{r}
#| label: sec12-1
#| cache: true
#| cache.comments: false

rsdatatmp <- rsdata %>%
  filter(shf_indexyear_cat == "2021-2023" & ATC_sos_lm_sglt2i == "A10BK01" & ATC_sos_lm_bbl == "C07AB07")

tab6mo <- rsdatatmp %>%
  filter(!is.na(fu_sos_lm_6mo)) %>%
  count(fu_sos_lm_6mo) %>%
  mutate(np = paste0(n, " (", fn(n / sum(n) * 100, 1), ")")) %>%
  mutate(
    np = case_when(
      n == 0 ~ "-",
      n < 10 ~ "<10",
      TRUE ~ np
    )
  ) %>%
  filter(fu_sos_lm_6mo == 1)
tab1yr <- rsdatatmp %>%
  filter(!is.na(fu_sos_lm_1yr)) %>%
  count(fu_sos_lm_1yr) %>%
  mutate(np = paste0(n, " (", fn(n / sum(n) * 100, 1), ")")) %>%
  mutate(
    np = case_when(
      n == 0 ~ "-",
      n < 10 ~ "<10",
      TRUE ~ np
    )
  ) %>%
  filter(fu_sos_lm_1yr == 1)
```

The number (%) of patients 2021-2023 taking dapagliflozin and bisoprolol and remaining on the combination at 6 months and 1 year is `r tab6mo %>% pull(np)` and `r tab1yr %>% pull(np)` respectively. 

```{r}
#| label: tab-sec12-2
#| cache: true
#| cache.comments: false
#| dependson: sec12-1
#| tbl-cap: "Secondary objective 12 - Change in dosage for patients taking dapagliflozin and bisoprolol at baseline and 6 months and 1 year 2021-2023"
#| tbl-pos: "H"

rsdatatmp <- rsdatatmp %>%
  mutate(
    dosechangebbl_6mo = factor(case_when(
      is.na(fu_sos_lm_6mo) | fu_sos_lm_6mo == 0 ~ NA_real_,
      dose_sos_lm_bbl == dosefu_sos_lm_C07AB07_6mo ~ 1,
      dose_sos_lm_bbl > dosefu_sos_lm_C07AB07_6mo ~ 2,
      dose_sos_lm_bbl < dosefu_sos_lm_C07AB07_6mo ~ 3
    ), levels = 1:3, labels = c("No change", "Decrease from baseline", "Increase from baseline")),
    dosechangesglt2i_6mo = factor(case_when(
      is.na(fu_sos_lm_6mo) | fu_sos_lm_6mo == 0 ~ NA_real_,
      dose_sos_lm_sglt2i == dosefu_sos_lm_A10BK01_6mo ~ 1,
      dose_sos_lm_sglt2i > dosefu_sos_lm_A10BK01_6mo ~ 2,
      dose_sos_lm_sglt2i < dosefu_sos_lm_A10BK01_6mo ~ 3
    ), levels = 1:3, labels = c("No change", "Decrease from baseline", "Increase from baseline")),
    dosechangebbl_1yr = factor(case_when(
      is.na(fu_sos_lm_1yr) | fu_sos_lm_1yr == 0 ~ NA_real_,
      dose_sos_lm_bbl == dosefu_sos_lm_C07AB07_1yr ~ 1,
      dose_sos_lm_bbl > dosefu_sos_lm_C07AB07_1yr ~ 2,
      dose_sos_lm_bbl < dosefu_sos_lm_C07AB07_1yr ~ 3
    ), levels = 1:3, labels = c("No change", "Decrease from baseline", "Increase from baseline")),
    dosechangesglt2i_1yr = factor(case_when(
      is.na(fu_sos_lm_1yr) | fu_sos_lm_1yr == 0 ~ NA_real_,
      dose_sos_lm_sglt2i == dosefu_sos_lm_A10BK01_1yr ~ 1,
      dose_sos_lm_sglt2i > dosefu_sos_lm_A10BK01_1yr ~ 2,
      dose_sos_lm_sglt2i < dosefu_sos_lm_A10BK01_1yr ~ 3
    ), levels = 1:3, labels = c("No change", "Decrease from baseline", "Increase from baseline")),
  )

tab6mo <- rsdatatmp %>%
  filter(!is.na(fu_sos_lm_6mo) & fu_sos_lm_6mo == 1) %>%
  count(dosechangebbl_6mo, dosechangesglt2i_6mo, .drop = F) %>%
  mutate(np = paste0(n, " (", fn(n / sum(n) * 100, 1), ")")) %>%
  mutate(
    np = case_when(
      n == 0 ~ "-",
      n < 10 ~ "<10",
      TRUE ~ np
    )
  ) %>%
  select(-n)
colnames(tab6mo) <- c("Change in Beta-blocker dose", "Change in SGLT2i dose", "6 months n (%)")

tab1yr <- rsdatatmp %>%
  filter(!is.na(fu_sos_lm_1yr) & fu_sos_lm_1yr == 1) %>%
  count(dosechangebbl_1yr, dosechangesglt2i_1yr, .drop = F) %>%
  mutate(np = paste0(n, " (", fn(n / sum(n) * 100, 1), ")")) %>%
  mutate(
    np = case_when(
      n == 0 ~ "-",
      n < 10 ~ "<10",
      TRUE ~ np
    )
  ) %>%
  select(-n)
colnames(tab1yr) <- c("Change in Beta-blocker dose", "Change in SGLT2i dose", "1 year n (%)")

tabboth <- full_join(tab6mo, tab1yr, by = c("Change in Beta-blocker dose", "Change in SGLT2i dose"))

# excel
if (output) {
  make_one_xlsxsheet(tabboth)
}

colnames(tabboth) <- sanitize_text(colnames(tabboth))

default_kable(tabboth,
  escape = FALSE,
  scale_down = T
)
```
