```{r}
#| label: sec3func
#| cache: true
#| cache.comments: false

coxvars <- modvars
coxvars[modvars %in% stratavars] <- paste0("strata(", coxvars[modvars %in% stratavars], ")")

sec3funcall <- function(data, impdata, type) {
  sec3func <- function(data, impdata, time, event, eventname, medvar,
                       novars = NULL, type) {
    coxvars <- setdiff(coxvars, novars)

    if (type == "adherence") {
      xvar <- paste0("sos_lmadhere_", medvar, "_cat")
    }
    if (type == "persistance") {
      xvar <- paste0("fu_sos_lm_", medvar)
    }

    levs <- levels(data %>% pull(!!sym(xvar)))
    nlevs <- length(levs)

    nrows <- 3
    out <- data.frame(matrix(NA, ncol = 2 + nlevs, nrow = nrows))
    colnames(out) <- c("Outcome", "Model", levs)

    out[1, 1] <- eventname

    ## incidence rate
    out[1, 2] <- "N events, incidence/100py (95% CI)"

    # 1 row - incidence
    ev <- data %>%
      filter(!is.na(!!sym(event))) %>%
      group_by(!!sym(xvar)) %>%
      summarise(
        ev = sum(!!sym(event) == "Yes"),
        s = sum(!!sym(time) / 365.25),
        .groups = "drop"
      )

    r <- pois.exact(x = ev$ev, pt = ev$s / 100)

    out[1, 3:(nlevs + 2)] <- paste0(
      ev$ev, ", ",
      fn(r$rate, dig = 0), " (",
      fn(r$lower, dig = 0), "-",
      fn(r$upper, dig = 0), ")"
    )

    if (all(ev$ev > 10)) {
      ## 2 row - crude regression
      out[2, 2] <- "Crude HR (95% CI), p-value"
      mod <- summary(coxph(formula(paste0("Surv(", time, ",", event, "== 'Yes') ~ ", xvar)),
        data = data
      ))

      out[2, 3:(nlevs + 2)] <- c(
        "reference",
        paste0(
          fn(mod$conf.int[, "exp(coef)"], dig = 2),
          " (", fn(mod$conf.int[, "lower .95"], dig = 2),
          "-", fn(mod$conf.int[, "upper .95"], dig = 2), "), ",
          fn(mod$coef[, "Pr(>|z|)"], dig = 3, p = TRUE)
        )
      )

      ## 3 row - adjusted regression
      out[3, 2] <- "Adjusted HR (95% CI), p-value"
      mod <- summary(pool(with(impdata, coxph(formula(paste0(
        "Surv(", time, ",", event, " == 'Yes') ~ ", xvar, "+", paste(coxvars, collapse = " + ")
      ))))))

      out[3, 3:(nlevs + 2)] <- c(
        "reference",
        paste0(
          fn(exp(mod$estimate[1:(nlevs - 1)]), dig = 2),
          " (", fn(exp(mod$estimate[1:(nlevs - 1)] - global_z05 * mod$std.error[1:(nlevs - 1)]), dig = 2),
          "-", fn(exp(mod$estimate[1:(nlevs - 1)] + global_z05 * mod$std.error[1:(nlevs - 1)]), dig = 2), "), ",
          fn(mod$p.value[1:(nlevs - 1)], dig = 3, p = TRUE)
        )
      )
    } else {
      out <- out[1, ]
    }
    return(out)
  }

  sec3func_outer <- function(medvar, byvar, lev, byvarname, novars, type) {
    if (type == "adherence") {
      stoptime <- 365
      xvar <- paste0("sos_lmadhere_", medvar, "_cat")
      addtimes <- "adhere"
    }
    if (type == "persistance") {
      stoptime <- 426
      xvar <- paste0("fu_sos_lm_", medvar)
      addtimes <- "disc"
    }

    if (is.null(byvar)) {
      impdata <- mice::filter(
        impdata,
        data %>%
          mutate(filt = !is.na(!!sym(xvar)) & sos_outtime_death >= stoptime) %>%
          pull(filt)
      )

      data <- data %>%
        filter(!is.na(!!sym(xvar)) & sos_outtime_death >= stoptime)
    } else {
      novars <- c(byvar, novars)

      impdata <- mice::filter(impdata, data %>%
        mutate(filt = !!sym(byvar) == lev & !is.na(!!sym(xvar)) &
          sos_outtime_death >= stoptime) %>% pull(filt))

      data <- data %>% filter(!!sym(byvar) == lev &
        !is.na(!!sym(xvar)) &
        sos_outtime_death >= stoptime)
    }

    out1 <- sec3func(
      data = data,
      impdata = impdata,
      time = paste0(outvars$time[1], addtimes),
      event = paste0(outvars$var[1], addtimes),
      eventname = outvars$shortname[1],
      medvar = medvar,
      novars = novars,
      type = type
    )
    out2 <- sec3func(
      data = data,
      impdata = impdata,
      time = paste0(outvars$time[2], addtimes),
      event = paste0(outvars$var[2], addtimes),
      eventname = outvars$shortname[2],
      medvar = medvar,
      novars = novars,
      type = type
    )
    out3 <- sec3func(
      data = data,
      impdata = impdata,
      time = paste0(outvars$time[3], addtimes),
      event = paste0(outvars$var[3], addtimes),
      eventname = outvars$shortname[3],
      medvar = medvar,
      novars = novars,
      type = type
    )
    outall <- rbind(out1, out2, out3)

    outall <- outall %>%
      add_column(
        Strata = paste0(byvarname, " ", lev),
        Medication = medvar,
        .before = 1
      )
  }

  medvars <- c("bbl", "rasiarni", "acei", "arb", "arni", "mra", "sglt2i")

  sec3func_outer2 <- function(byvar = NULL, lev = NULL, byvarname, novars = NULL, type) {
    out <- lapply(medvars,
      FUN = sec3func_outer,
      byvar = byvar, byvarname = byvarname, lev = lev, novars = novars, type = type
    )

    out <- bind_rows(out)
  }

  sec3func_outer3 <- function(byvar, byvarname, novars = NULL, type) {
    out <- lapply(levels(data %>% pull(!!sym(byvar))),
      FUN = sec3func_outer2,
      byvar = byvar, byvarname = byvarname, novars = novars, type = type
    )

    out <- bind_rows(out)
  }

  overall <- sec3func_outer2(byvar = NULL, byvarname = "Overall", novars = NULL, type = type)

  sos_prevhfh3mo <- sec3func_outer3(byvar = "sos_prevhfh3mo", byvarname = "HFH within 3 months", type = type)

  age <- sec3func_outer3(byvar = "shf_age_cat", byvarname = "Age", type = type)

  sex <- sec3func_outer3(byvar = "shf_sex", byvarname = "", type = type)

  egfr <- sec3func_outer3(byvar = "shf_gfrckdepi_cat", byvarname = "eGFR", type = type)

  cci <- sec3func_outer3(byvar = "sos_com_charlsonci_cat", byvarname = "Charlson Comorbidity Index", type = type)

  meds <- sec3func_outer3(byvar = "sos_lm_n_othermeds_cat", byvarname = "Other medications", type = type)

  outall <- bind_rows(overall, sos_prevhfh3mo, age, sex, egfr, cci, meds)
}
```

```{r}
#| label: tbl-sec3-adherence
#| cache: true
#| cache.comments: false
#| dependson: sec3func
#| tbl-cap: "Association between adherence and outcomes"

outall <- sec3funcall(data = rsdata, impdata = imprsdata, type = "adherence")

outall <- outall %>%
  mutate(Medication = factor(case_when(
    Medication == "bbl" ~ 1,
    Medication == "rasiarni" ~ 2,
    Medication == "acei" ~ 3,
    Medication == "arb" ~ 4,
    Medication == "arni" ~ 5,
    Medication == "mra" ~ 6,
    Medication == "sglt2i" ~ 7,
  ), levels = 1:7, labels = c("Beta-blocker", "ACEi/ARB/ARNi", "ACEi", "ARB", "ARNi", "MRA", "SGLT2i")))

if (output) {
  make_one_xlsxsheet(outall)
}

outall <- outall %>%
  mutate(Strata = str_squish(Strata)) %>%
  mutate(across(everything(), sanitize_text)) %>%
  mutate(
    Strata = str_replace_all(Strata, fixed("$>$="), "$\\geq$"),
    Strata = str_replace_all(Strata, fixed("$<$="), "$\\leq$")
  ) %>%
  group_by(Strata, Medication) %>%
  mutate(
    c = 1:n(),
    Medication = if_else(c == 1, Medication, "")
  ) %>%
  ungroup() %>%
  group_by(Strata) %>%
  mutate(
    c = 1:n(),
    Strata = if_else(c == 1, Strata, "")
  ) %>%
  ungroup() %>%
  select(-c)

colnames(outall) <- sanitize_text(colnames(outall))
colnames(outall) <- str_replace_all(colnames(outall), fixed("$>$="), "$\\geq$")
colnames(outall) <- str_replace_all(colnames(outall), fixed("$<$="), "$\\leq$")

default_kable(outall,
  longtable = TRUE,
  font_size = 4.5,
  escape = F
) %>%
  add_header_above(c(" " = 4, "Adherence" = 2)) %>%
  footnote(
    footnote_order = c("general", "symbol", "alphabet"),
    general_title = "",
    general = c(
      "Cox regressions are performed if the number of events > 10 in both groups.",
      "Abbreviations: py, person-years; HR, Hazard Ratio; CVM, Cardiovascular mortality; HFH, Heart failure hospitalisation"
    ),
    threeparttable = T
  )
```

```{r}
#| label: tbl-sec3-adherence-2021-2023
#| cache: true
#| cache.comments: false
#| dependson: sec3func
#| tbl-cap: "Association between adherence and outcomes 2021-2023"


outall <- sec3funcall(
  data = rsdata %>% filter(shf_indexyear_cat == "2021-2023"),
  impdata = mice::filter(imprsdata, rsdata$shf_indexyear_cat == "2021-2023"),
  type = "adherence"
)

outall <- outall %>%
  mutate(Medication = factor(case_when(
    Medication == "bbl" ~ 1,
    Medication == "rasiarni" ~ 2,
    Medication == "acei" ~ 3,
    Medication == "arb" ~ 4,
    Medication == "arni" ~ 5,
    Medication == "mra" ~ 6,
    Medication == "sglt2i" ~ 7,
  ), levels = 1:7, labels = c("Beta-blocker", "ACEi/ARB/ARNi", "ACEi", "ARB", "ARNi", "MRA", "SGLT2i")))

if (output) {
  make_one_xlsxsheet(outall)
}

outall <- outall %>%
  mutate(Strata = str_squish(Strata)) %>%
  mutate(across(everything(), sanitize_text)) %>%
  mutate(
    Strata = str_replace_all(Strata, fixed("$>$="), "$\\geq$"),
    Strata = str_replace_all(Strata, fixed("$<$="), "$\\leq$")
  ) %>%
  group_by(Strata, Medication) %>%
  mutate(
    c = 1:n(),
    Medication = if_else(c == 1, Medication, "")
  ) %>%
  ungroup() %>%
  group_by(Strata) %>%
  mutate(
    c = 1:n(),
    Strata = if_else(c == 1, Strata, "")
  ) %>%
  ungroup() %>%
  select(-c)

colnames(outall) <- sanitize_text(colnames(outall))
colnames(outall) <- str_replace_all(colnames(outall), fixed("$>$="), "$\\geq$")
colnames(outall) <- str_replace_all(colnames(outall), fixed("$<$="), "$\\leq$")

default_kable(outall,
  longtable = TRUE,
  font_size = 4.5,
  escape = F
) %>%
  add_header_above(c(" " = 4, "Adherence" = 2)) %>%
  footnote(
    footnote_order = c("general", "symbol", "alphabet"),
    general_title = "",
    general = c(
      "Cox regressions are performed if the number of events > 10 in both groups.",
      "Abbreviations: py, person-years; HR, Hazard Ratio; CVM, Cardiovascular mortality; HFH, Heart failure hospitalisation"
    ),
    threeparttable = T
  )
```

```{r}
#| label: tbl-sec3-persistance
#| cache: true
#| cache.comments: false
#| dependson: sec3func
#| tbl-cap: "Association between persistance and outcomes"

outall <- sec3funcall(data = rsdata, impdata = imprsdata, type = "persistance")

outall <- outall %>%
  mutate(Medication = factor(case_when(
    Medication == "bbl" ~ 1,
    Medication == "rasiarni" ~ 2,
    Medication == "acei" ~ 3,
    Medication == "arb" ~ 4,
    Medication == "arni" ~ 5,
    Medication == "mra" ~ 6,
    Medication == "sglt2i" ~ 7,
  ), levels = 1:7, labels = c("Beta-blocker", "ACEi/ARB/ARNi", "ACEi", "ARB", "ARNi", "MRA", "SGLT2i")))

if (output) {
  make_one_xlsxsheet(outall)
}

outall <- outall %>%
  mutate(Strata = str_squish(Strata)) %>%
  mutate(across(everything(), sanitize_text)) %>%
  mutate(
    Strata = str_replace_all(Strata, fixed("$>$="), "$\\geq$"),
    Strata = str_replace_all(Strata, fixed("$<$="), "$\\leq$")
  ) %>%
  group_by(Strata, Medication) %>%
  mutate(
    c = 1:n(),
    Medication = if_else(c == 1, Medication, "")
  ) %>%
  ungroup() %>%
  group_by(Strata) %>%
  mutate(
    c = 1:n(),
    Strata = if_else(c == 1, Strata, "")
  ) %>%
  ungroup() %>%
  select(-c)

colnames(outall) <- sanitize_text(colnames(outall))
colnames(outall) <- str_replace_all(colnames(outall), fixed("$>$="), "$\\geq$")
colnames(outall) <- str_replace_all(colnames(outall), fixed("$<$="), "$\\leq$")

default_kable(outall,
  longtable = TRUE,
  font_size = 4.5,
  escape = F
) %>%
  add_header_above(c(" " = 4, "Persistance" = 2)) %>%
  footnote(
    footnote_order = c("general", "symbol", "alphabet"),
    general_title = "",
    general = c(
      "Cox regressions are performed if the number of events > 10 in both groups.",
      "Abbreviations: py, person-years; HR, Hazard Ratio; CVM, Cardiovascular mortality; HFH, Heart failure hospitalisation"
    ),
    threeparttable = T
  )
```

```{r}
#| label: tbl-sec3-persistance-2021-2023
#| cache: true
#| cache.comments: false
#| dependson: sec3func
#| tbl-cap: "Association between persistance and outcomes 2021-2023"


outall <- sec3funcall(
  data = rsdata %>% filter(shf_indexyear_cat == "2021-2023"),
  impdata = mice::filter(imprsdata, rsdata$shf_indexyear_cat == "2021-2023"),
  type = "persistance"
)

outall <- outall %>%
  mutate(Medication = factor(case_when(
    Medication == "bbl" ~ 1,
    Medication == "rasiarni" ~ 2,
    Medication == "acei" ~ 3,
    Medication == "arb" ~ 4,
    Medication == "arni" ~ 5,
    Medication == "mra" ~ 6,
    Medication == "sglt2i" ~ 7,
  ), levels = 1:7, labels = c("Beta-blocker", "ACEi/ARB/ARNi", "ACEi", "ARB", "ARNi", "MRA", "SGLT2i")))

if (output) {
  make_one_xlsxsheet(outall)
}

outall <- outall %>%
  mutate(Strata = str_squish(Strata)) %>%
  mutate(across(everything(), sanitize_text)) %>%
  mutate(
    Strata = str_replace_all(Strata, fixed("$>$="), "$\\geq$"),
    Strata = str_replace_all(Strata, fixed("$<$="), "$\\leq$")
  ) %>%
  group_by(Strata, Medication) %>%
  mutate(
    c = 1:n(),
    Medication = if_else(c == 1, Medication, "")
  ) %>%
  ungroup() %>%
  group_by(Strata) %>%
  mutate(
    c = 1:n(),
    Strata = if_else(c == 1, Strata, "")
  ) %>%
  ungroup() %>%
  select(-c)

colnames(outall) <- sanitize_text(colnames(outall))
colnames(outall) <- str_replace_all(colnames(outall), fixed("$>$="), "$\\geq$")
colnames(outall) <- str_replace_all(colnames(outall), fixed("$<$="), "$\\leq$")

default_kable(outall,
  longtable = TRUE,
  font_size = 4.5,
  escape = F
) %>%
  add_header_above(c(" " = 4, "Persistance" = 2)) %>%
  footnote(
    footnote_order = c("general", "symbol", "alphabet"),
    general_title = "",
    general = c(
      "Cox regressions are performed if the number of events > 10 in both groups.",
      "Abbreviations: py, person-years; HR, Hazard Ratio; CVM, Cardiovascular mortality; HFH, Heart failure hospitalisation"
    ),
    threeparttable = T
  )
```
