```{r}
#| label: tbl-furosemide-dose
#| cache: true
#| cache.comments: false
#| tbl-cap: "Dose"
#| tbl-pos: "H"

tab <- rsdata %>%
  filter(shf_indexyear_cat == "2021-2023" & ATC_sos_lm_loopdiuretics == "C03CA01") %>%
  count(dose_sos_lm_loopdiuretics) %>%
  mutate(
    np = paste0(n, " (", fn(n / sum(n) * 100, 1), ")")
  ) %>%
  filter(n > 10) %>%
  select(dose_sos_lm_loopdiuretics, np)

colnames(tab) <- c("Furosemide dose (mg)", "N (%)")
# excel
make_one_xlsxsheet(tab)

default_kable(tab,
  escape = TRUE,
  scale_down = F
)
```

```{r}
#| label: tbl-furosemide
#| cache: true
#| cache.comments: false
#| tbl-cap: "Change in dosage for patients taking furosemide at baseline and 6 months and 1 year 2021-2023"
#| tbl-pos: "H"

rsdatatmp <- rsdata %>%
  filter(shf_indexyear_cat == "2021-2023" & ATC_sos_lm_loopdiuretics == "C03CA01") %>%
  mutate(
    dosechange_6mo = factor(case_when(
      is.na(fu_sos_lm_6mo) | fu_sos_lm_6mo == 0 ~ NA_real_,
      dose_sos_lm_loopdiuretics == dosefu_sos_lm_C03CA01_6mo ~ 1,
      dose_sos_lm_loopdiuretics > dosefu_sos_lm_C03CA01_6mo ~ 2,
      dose_sos_lm_loopdiuretics < dosefu_sos_lm_C03CA01_6mo ~ 3
    ), levels = 1:3, labels = c("No change", "Decrease from baseline", "Increase from baseline")),
    dosechange_1yr = factor(case_when(
      is.na(fu_sos_lm_1yr) | fu_sos_lm_1yr == 0 ~ NA_real_,
      dose_sos_lm_loopdiuretics == dosefu_sos_lm_C03CA01_1yr ~ 1,
      dose_sos_lm_loopdiuretics > dosefu_sos_lm_C03CA01_1yr ~ 2,
      dose_sos_lm_loopdiuretics < dosefu_sos_lm_C03CA01_1yr ~ 3
    ), levels = 1:3, labels = c("No change", "Decrease from baseline", "Increase from baseline"))
  )

tab6mo <- rsdatatmp %>%
  filter(!is.na(fu_sos_lm_6mo) & fu_sos_lm_6mo == 1 & !is.na(dosefu_sos_lm_C03CA01_6mo)) %>%
  count(dosechange_6mo, .drop = F) %>%
  mutate(np = paste0(n, " (", fn(n / sum(n) * 100, 1), ")")) %>%
  mutate(
    np = case_when(
      n < 10 ~ "<10",
      TRUE ~ np
    )
  )
tab6mon <- rsdatatmp %>%
  filter(!is.na(fu_sos_lm_6mo) & fu_sos_lm_6mo == 1 & !is.na(dosefu_sos_lm_C03CA01_6mo)) %>%
  count() %>%
  mutate(np = paste0(n)) %>%
  mutate(
    np = case_when(
      n < 10 ~ "<10",
      TRUE ~ np
    ),
    dosechange_6mo = "N"
  )
tab6mo <- rbind(tab6mon, tab6mo) %>% select(dosechange_6mo, np)

tab1yr <- rsdatatmp %>%
  filter(!is.na(fu_sos_lm_1yr) & fu_sos_lm_1yr == 1 & !is.na(dosefu_sos_lm_C03CA01_1yr)) %>%
  count(dosechange_1yr, .drop = F) %>%
  mutate(np = paste0(n, " (", fn(n / sum(n) * 100, 1), ")")) %>%
  mutate(
    np = case_when(
      n < 10 ~ "<10",
      TRUE ~ np
    )
  )

tab1yrn <- rsdatatmp %>%
  filter(!is.na(fu_sos_lm_1yr) & fu_sos_lm_1yr == 1 & !is.na(dosefu_sos_lm_C03CA01_1yr)) %>%
  count() %>%
  mutate(np = paste0(n)) %>%
  mutate(
    np = case_when(
      n < 10 ~ "<10",
      TRUE ~ np
    ),
    dosechange_1yr = "N"
  )
tab1yr <- rbind(tab1yrn, tab1yr) %>% select(dosechange_1yr, np)

colnames(tab6mo) <- c("Change in Furosemide dose", "6 months")
colnames(tab1yr) <- c("Change in Furosemide dose", "1 year")

tabboth <- full_join(tab6mo, tab1yr, by = c("Change in Furosemide dose"))

# excel
make_one_xlsxsheet(tabboth)


default_kable(tabboth,
  escape = TRUE,
  scale_down = F
)
```
